fix: Poll tasks sequentially again but process them concurrently
samply/focus pull request #123
Opened 2024-03-18 13:07 UTC by Threated

I moved the original `proccess_task` function back to main as the task_processing.rs file is now mostly concerned about the beam task life cycle. And not about the logic that goes into generating a result based on a beam task.
Just to be clear I dont think this will fix the dktk problem but it might.

2024-03-18 14:40 UTC, enola-dkfz approved these changes
You explained it to me, my brain hurts, but LGTM

2024-03-21 06:58 UTC, TKussel requested changes

2024-03-21 06:58 UTC, TKussel commented on src/main.rs
> +        EndpointType::Omop => || async { true }.boxed(), // TODO health check
This is a bit cursed :D
However, no changes proposed.

2024-03-21 06:58 UTC, TKussel commented on src/main.rs
> +            return ExitCode::from(22);
As a todo on the roadmap: I would love to replace that with a (bounded) exponential backoff.

2024-03-21 06:58 UTC, TKussel commented on src/main.rs
> +    let obf_cache = Arc::new(Mutex::new(ObfCache {
Why do you use a "raw" Mutex? For caches, I would assume that a RWLock is better suited?

2024-03-21 06:58 UTC, TKussel commented on src/main.rs
> +use base64::engine::general_purpose;
Where do you need this import?

2024-03-21 06:58 UTC, TKussel commented on src/task_processing.rs
> +pub async fn process_tasks<F>(task_hanlder: F)
```suggestion
pub async fn process_tasks<F>(task_handler: F)
```

2024-03-21 06:58 UTC, TKussel commented on src/task_processing.rs
> +    stream_task_results(task_hanlder)
```suggestion
    stream_task_results(task_handler)
```

2024-03-21 06:58 UTC, TKussel commented on src/task_processing.rs
> +        debug!("Successfully claimed task");
Maybe add task id to log?

2024-03-21 06:58 UTC, TKussel commented on src/task_processing.rs
> +                let mut task_claiming = std::pin::pin!(beam::claim_task(&task2));
Why do you need to pin here?

2024-03-21 06:58 UTC, TKussel commented on src/task_processing.rs
> +                        tracing::debug!("Proccessed task before claimed");
That should be a warn, as it would indicate flow issues, right?

2024-03-21 08:10 UTC, Threated commented on src/task_processing.rs
> +        debug!("Successfully claimed task");
Done automagically by the tracing span

2024-03-21 08:14 UTC, Threated commented on src/task_processing.rs
> +                let mut task_claiming = std::pin::pin!(beam::claim_task(&task2));
I need it because I need to select on a &mut in the select so I can poll the claiming future to completion in the rare case where it is slower than executing the query.

2024-03-21 08:16 UTC, Threated commented on src/task_processing.rs
> +                        tracing::debug!("Proccessed task before claimed");
Not really it just means that somehow claiming the task in beam took longer than executing the query but this may be the case when focus has cached something or only executes some api request against the exporter I guess

2024-03-21 08:18 UTC, Threated commented on src/main.rs
> +use base64::engine::general_purpose;
I moved `proccess_task` back into main as task_processing is now very specific to the beam task lifecycle and this function need it I think but will double check before merging

2024-03-21 08:20 UTC, Threated commented on src/main.rs
> +    let obf_cache = Arc::new(Mutex::new(ObfCache {
I just left it as it was before and did not want to change more than I needed to but I agree

2024-03-21 08:21 UTC, Threated commented
I noticed this does not quite work as I want it to so please dont merge yet

2024-05-14 08:41 UTC, merged