updated readme
samply/focus pull request #14
Opened 2023-03-28 12:10 UTC by enola-dkfz

2023-03-28 14:37 UTC, TKussel requested changes

2023-03-28 14:37 UTC, TKussel commented on README.md
> +docker run --rm -e BEAM_BASE_URL=http://localhost:8081 -e BLAZE_BASE_URL=http://localhost:8089/fhir -e PROXY_ID=proxy1.broker -e API_KEY=App1Secret -e BEAM_APP_ID_LONG=app1 samply/focus:latest
Nomenclature wise, `BEAM_APP_ID_LONG` should refer to `app1.broker.example.com`. For the short name, either `BEAM_APP_ID` or `BEAM_APP_ID_SHORT` would be better suited.

2023-03-28 14:37 UTC, TKussel commented on README.md
> +BEAM_APP_ID_LONG = "app1"
Same as in line 17.

2023-03-29 10:06 UTC, enola-dkfz commented on README.md
> +docker run --rm -e BEAM_BASE_URL=http://localhost:8081 -e BLAZE_BASE_URL=http://localhost:8089/fhir -e PROXY_ID=proxy1.broker -e API_KEY=App1Secret -e BEAM_APP_ID_LONG=app1 samply/focus:latest
done, there's only the long one

2023-03-29 10:06 UTC, enola-dkfz commented on README.md
> +BEAM_APP_ID_LONG = "app1"
done, there's only the long one

2023-03-29 12:37 UTC, TKussel approved these changes

2023-03-29 12:37 UTC, merged