CQL generation and some other stuff
samply/focus pull request #151
Opened 2024-06-13 14:06 UTC by enola-dkfz

backward compatibility preserved
when CQL generation needs to be turned on for BBMRI/GBN in focus, switch to image main-bbmri

2024-06-13 14:07 UTC, enola-dkfz commented
Do not merge before all the presentations on 14th June 2024 are done!

2024-06-14 15:06 UTC, Threated requested changes

2024-06-14 15:06 UTC, Threated commented on src/cql.rs
> +                            }
In some other cases this can also be achieved using let else syntax but here we want to create a nice error as you did so we need to know the value of other hence I suggested the match

2024-06-14 15:06 UTC, Threated commented on src/cql.rs
> +                        }
Same as above

2024-06-14 15:06 UTC, Threated commented on src/cql.rs
> +                ));
I don't even know what if this else belongs to anymore consider using let else if it was a match or a guard statement if it was a regular check to save indentation and make it more readable

2024-06-17 07:59 UTC, lablans requested changes

2024-06-17 07:59 UTC, lablans commented on Cargo.toml
>  beam-lib = { git = "https://github.com/samply/beam", branch = "develop", features = ["http-util"] }
Note that you use develop branch here. Intended?

2024-06-17 07:59 UTC, lablans commented on Cargo.toml
Increase version number?

2024-06-17 07:59 UTC, lablans commented on Cargo.toml
> +
Too many newlines?

2024-06-17 07:59 UTC, lablans commented on README.md
> +Creating a sample task containing an abstract syntax tree (AST) query using CURL:
```suggestion
Creating a sample task containing an abstract syntax tree (AST) query using curl:
```

2024-06-17 07:59 UTC, lablans commented on README.md
> +Creating a sample [Exporter](https://github.com/samply/exporter) "status" task using CURL:
```suggestion
Creating a sample [Exporter](https://github.com/samply/exporter) "status" task using curl:
```

2024-06-17 07:59 UTC, lablans commented on README.md
> +Creating a sample task containing a [Blaze](https://github.com/samply/blaze) query using CURL:
```suggestion
Creating a sample task containing a [Blaze](https://github.com/samply/blaze) query using curl:
```

2024-06-17 07:59 UTC, lablans commented on src/ast.rs
> +pub enum Operand { //this is operator, of course, but rename would need to be coordinated with all the Lenses, EUCAIM providers, etc
Please do coordinate this, should be possible with a rather simple search/replace.

2024-06-17 07:59 UTC, lablans commented on src/blaze.rs
> +pub fn parse_blaze_query_payload_ast(ast_query: &String) -> Result<ast::Ast, FocusError> {
```suggestion
pub fn parse_blaze_query_payload_ast(ast_query: &str) -> Result<ast::Ast, FocusError> {
```

2024-06-17 07:59 UTC, lablans commented on src/errors.rs
> +    #[error("Mismatch between operator and value type")]
```suggestion
    #[error("Mismatch between operator and value type: {0}")]
```

2024-06-17 07:59 UTC, lablans commented on src/util.rs
> +    let mut rng = thread_rng();// TODO evict
Not sure we need to "evict" this, I believe this is already fine. See chat.

2024-06-17 08:08 UTC, enola-dkfz commented on Cargo.toml
>  beam-lib = { git = "https://github.com/samply/beam", branch = "develop", features = ["http-util"] }
that's a question for @Threated

2024-06-17 08:09 UTC, enola-dkfz commented on Cargo.toml
sure

2024-06-17 08:10 UTC, Threated commented on Cargo.toml
>  beam-lib = { git = "https://github.com/samply/beam", branch = "develop", features = ["http-util"] }
Yes

2024-06-17 08:11 UTC, enola-dkfz commented on resources/test/result.cql
remnant of past, will delete

2024-06-19 08:55 UTC, enola-dkfz commented on src/ast.rs
> +pub enum Operand { //this is operator, of course, but rename would need to be coordinated with all the Lenses, EUCAIM providers, etc
I will, but it can't be done before this merge because it is a breaking change for the providers.

2024-06-19 11:40 UTC, enola-dkfz commented on src/cql.rs
> +                            }
Point taken, however, it could happen that in the (near) future we allow the IN criterion for other types than string array, for example on num array, and then the code itself would differ, as in the BETWEEN criterion for example. In any case I intend to rewrite the entire CQL generation in a more functional way.

2024-06-19 12:39 UTC, Threated approved these changes

2024-06-19 13:04 UTC, lablans approved these changes

2024-06-20 12:08 UTC, merged