more logging
samply/focus pull request #156
Opened 2024-07-16 18:03 UTC by enola-dkfz

2024-07-16 18:21 UTC, Threated approved these changes

2024-07-16 20:20 UTC, TKussel requested changes
Looks great, however, please add the warning during startup if trace log level is selected.

2024-07-16 20:20 UTC, TKussel commented on src/main.rs
> +            trace!("MeasureReport with unobfuscated values: {}", &cql_result);
As the trace level now logs unobfuscated results, I would like to see a fat warning during startup, if `trace` is selected.

2024-07-17 07:14 UTC, enola-dkfz commented on src/main.rs
> +            trace!("MeasureReport with unobfuscated values: {}", &cql_result);
made a new PR into develop with that

2024-07-17 07:34 UTC, TKussel approved these changes

2024-07-17 07:35 UTC, TKussel commented
The comment is addressed in #157

2024-07-17 09:37 UTC, merged