Feature/sql
samply/focus pull request #158
Opened 2024-07-17 17:26 UTC by enola-dkfz

2024-07-18 10:41 UTC, davidmscholz approved these changes

2024-07-18 12:01 UTC, TKussel approved these changes
lgtm, the comments are not blockers but things to discuss and put into the backlog

2024-07-18 12:02 UTC, Threated requested changes

2024-07-18 12:02 UTC, Threated commented on src/main.rs
> +        }
This should never happen? As we have listed all types of endpoint here but the compiler cant help us because we did not use a match but a bunch of ifs which we should change

2024-07-18 12:02 UTC, Threated commented on src/main.rs
> +            }
Again this is pretty much a repetition of the above just because we now have this endpoint type for both we should really find a better way to do this. In this section are also some of the same points I complained about above

2024-07-18 12:06 UTC, enola-dkfz commented on README.md
> +ENDPOINT_TYPE = "blaze" # Type of the endpoint, allowed values: "blaze", "omop", "sql", "blaze-and-sql"; default value: "blaze"
It's even more complicated than that. We have query language in the body of the task itself, for Blaze it can be CQL and AST, for now, should also be GraphQL in the future. So, we really have 2 endpoints, Blaze, and a separate Postgres. Oh, there's another thing. Exporter. It also has Blaze, but the project in the metadata of the task says exporter, so Focus knows to query the exporter, and that exporter is going to query blaze.

2024-07-18 12:09 UTC, enola-dkfz commented on build.rs
> +    let mut file = BufWriter::new(File::create(path).unwrap());
I just duplicated the way Martin did it for CQL snippets. It has been running in PROD that way since January.

2024-07-18 12:10 UTC, enola-dkfz commented on build.rs
> +        let sqlcontent = std::fs::read_to_string(sqlfile.path()).unwrap();
I could do expect instead. Should I?

2024-07-18 12:51 UTC, enola-dkfz commented on src/db.rs
> +                );
You're right, changing to warn.

2024-07-19 11:56 UTC, enola-dkfz commented on src/main.rs
> +            }
Yes, we need restructuring, and it might involve breaking changes because if we keep backward compatibility it will probably never be removed.

2024-07-19 12:28 UTC, TKussel commented on src/db.rs
> +    let query = sql_query.unwrap();
Filtering is not the way to go. Properly using prepared statements is how you avoid sql injections.

2024-07-19 12:31 UTC, enola-dkfz commented on src/db.rs
> +    let query = sql_query.unwrap();
It is not only about preventing SQL injections, there are about 6 queries total that are going to be allowed.

2024-07-19 13:48 UTC, enola-dkfz commented on src/db.rs
> +    let res = run_query(pool, SQL_REPLACE_MAP.get("SELECT_TABLES").unwrap()).await; //this file exists, safe to unwrap
at the moment this is to be used we already have the pool, so no need to do the checking
I only use the function for testing during development and the tests are commented out to not run in CI/CD
I will remove the function

2024-07-19 13:55 UTC, enola-dkfz commented on src/config.rs
> +    db_connection_string: Option<String>,
renamed to postgres_connection_string

2024-07-19 13:57 UTC, enola-dkfz commented on src/main.rs
> +            serde_json::from_slice(&(data.clone()));
considered it, gave up because it's not a Blaze query, although sometimes it is OK that is comes to the endpoints that also have Blaze
but because we need to allow multiple stores at a site, and multiple language and store combinations, let's leave it for the focus restructuring

2024-07-19 14:01 UTC, enola-dkfz commented on src/main.rs
> +                if let Ok(rows) = result {
I somehow always forget about the existence of the ?

2024-07-19 14:09 UTC, enola-dkfz commented on src/main.rs
> +        }
yeah, can it be left for the great restructuring?

2024-07-19 14:11 UTC, Threated commented on src/main.rs
> +        }
I mean changing all the else ifs to a match should be very easy plus you can remove the else arm. I would like it in here

2024-07-19 14:18 UTC, enola-dkfz commented on src/main.rs
> +            }
OK, that can be done now

2024-07-19 14:19 UTC, enola-dkfz commented on src/main.rs
> +        }
ok that can be done now

2024-07-22 13:08 UTC, enola-dkfz commented on src/db.rs
> +    let res = run_query(pool, SQL_REPLACE_MAP.get("SELECT_TABLES").unwrap()).await; //this file exists, safe to unwrap
I will remove the function and the tests once you OK it (need them to test if I make any changes). I think @davidmscholz would like to add some serialization tests.

2024-07-22 13:19 UTC, Threated requested changes
Apart from my comment about the retry lib it looks good

2024-07-22 13:19 UTC, Threated commented on Cargo.toml
> +tokio-retry = "0.3"
The only well maintained lib for retry I found is https://docs.rs/tryhard/latest/tryhard/ so I would suggest using it

2024-07-22 13:32 UTC, Threated approved these changes

2024-07-22 13:36 UTC, enola-dkfz commented on src/db.rs
> +    let res = run_query(pool, SQL_REPLACE_MAP.get("SELECT_TABLES").unwrap()).await; //this file exists, safe to unwrap
removed

2024-07-22 13:40 UTC, merged