Postgres querying etc.
samply/focus pull request #164
Opened 2024-09-03 11:43 UTC by enola-dkfz

2024-09-03 12:24 UTC, enola-dkfz commented
there's a security issue in sqlx, its version needs to be increased to at least 0.8.1, that's the last version ATM, they have messed up and it doesn't compile
additionally, sqlx-pgrow-serde depends on that messed up version of sqlx

2024-10-07 08:33 UTC, TKussel requested changes

2024-10-07 08:33 UTC, TKussel commented on CHANGELOG.md
> +* PostgreSQL support added
```suggestion
# Samply.Focus v0.7.0 2024-09-24

In this release, we are extending the supported data backends beyond CQL-enabled FHIR stores. We now support PostgreSQL as well. Usage instructions are included in the Readme.

## Major changes
* PostgreSQL support added
```

Please adapt date before merging and add a couple of lines rgarding usage/feature flags in the readme.

2024-10-07 08:33 UTC, TKussel commented on Cargo.toml
> +kurtbuilds_sqlx_serde = { version = "0.3.2", features = [ "json", "decimal", "chrono", "uuid"], optional = true }
You wanted to replace that, right?

2024-10-07 08:33 UTC, TKussel commented on README.md
Please add a "How to" for Postgres, as it needs to be compiled with a different feature flag

2024-10-07 08:33 UTC, TKussel commented on src/errors.rs
> +    ErrorExecutingQuery(sqlx::Error),
That error can be useful for blaze as well, no? Why is it hidden behind the feature gate?

2024-10-07 08:33 UTC, TKussel commented on src/db.rs
> +            .max_connections(10)
In my opinion, that should not be hard coded.

2024-10-07 08:33 UTC, TKussel commented on src/db.rs
> +    tryhard::retry_fn(|| async {
Thanks for implementing exponential backoff!

2024-10-07 08:33 UTC, TKussel commented on src/db.rs
> +    .exponential_backoff(Duration::from_secs(2))
Is that bounded, i.e., exponentially increasing the backoff time up to an upper bound? If not, consider doing that (up to 30 seconds or so).

2024-10-07 08:33 UTC, TKussel commented on src/db.rs
> +    debug!("Executing query {}", &query);
Do the query or the key potentially include sensitive information? If yes, please do not log.

2024-10-07 08:39 UTC, enola-dkfz commented on src/db.rs
> +    debug!("Executing query {}", &query);
This is a question for @davidmscholz

2024-10-07 08:41 UTC, enola-dkfz commented on src/db.rs
> +    .exponential_backoff(Duration::from_secs(2))
Is max_attempts not enough?

2024-10-07 09:21 UTC, Threated commented on src/errors.rs
> +    ErrorExecutingQuery(sqlx::Error),
This Error contains an `sqlx::Error` so it can't be used otherwise. It should probably be renamed.

2024-10-07 09:22 UTC, Threated approved these changes

2024-10-07 12:07 UTC, enola-dkfz commented on Cargo.toml
> +kurtbuilds_sqlx_serde = { version = "0.3.2", features = [ "json", "decimal", "chrono", "uuid"], optional = true }
I didn't need to in the end, @davidmscholz is OK with floats becoming strings

2024-10-07 12:24 UTC, enola-dkfz commented on CHANGELOG.md
> +* PostgreSQL support added
But we have had EUCAIM querying as well

2024-10-07 12:25 UTC, enola-dkfz commented on README.md
here: https://github.com/samply/focus/pull/171

2024-10-07 12:25 UTC, enola-dkfz commented on src/errors.rs
> +    ErrorExecutingQuery(sqlx::Error),
Renamed

2024-10-07 12:26 UTC, enola-dkfz commented on src/db.rs
> +    debug!("Executing query {}", &query);
@davidmscholz said in the review that the query shouldn't contain anything sensitive

2024-10-07 12:29 UTC, enola-dkfz commented on src/db.rs
> +    tryhard::retry_fn(|| async {
❤️

2024-10-07 14:54 UTC, TKussel approved these changes

2024-10-08 06:50 UTC, TKussel commented on src/db.rs
> +            .max_connections(10)
While I am not a fan of the growing forrest of command line parameters, I think that would be the most "proper" way. Or pull it out into a constant for the time being.

2024-10-08 06:54 UTC, TKussel commented on src/db.rs
> +    .exponential_backoff(Duration::from_secs(2))
Usually, exponential backoff uses an exponent of 2, so the wait times can grow unreasonably large even with "moderate" retries. Here with 10 retries and 2 seconds start delay, the last attempt would wait for 17 minutes. I think this is ok, just a potential footgun while tweaking the parameters.

2024-10-09 09:53 UTC, davidmscholz approved these changes
Querying with SQL worked as expected for the (basic) datatypes I tested.

2024-10-10 10:42 UTC, enola-dkfz commented on src/db.rs
> +            .max_connections(10)
don't worry, it's behind a feature

2024-10-11 10:43 UTC, enola-dkfz commented on CHANGELOG.md
> +* PostgreSQL support added
I just meant the formulation, but I did it as you suggested.

2024-10-11 10:44 UTC, enola-dkfz commented on src/db.rs
> +            .max_connections(10)
done

2024-10-11 10:44 UTC, enola-dkfz commented on src/db.rs
> +    .exponential_backoff(Duration::from_secs(2))
it was 8, now it's a CL arg, default 8

2024-10-14 13:43 UTC, merged