Feature/all fhir here
samply/focus pull request #17
Opened 2023-04-06 13:13 UTC by enola-dkfz

2023-04-06 20:34 UTC, TKussel requested changes
Only a few minor nitpicks.

2023-04-06 20:34 UTC, TKussel commented on src/main.rs
>      //debug!("_________________________________________________________");
Please remove commented out code and debug messages. In this instance, you could either argue that a) the debug output should be demoted to trace level, but can help to diagnose very specific errors, or b) that no sensitive information (i.e. mapping from clear value to obfuscated) should be logged.

2023-04-06 20:34 UTC, TKussel commented on src/main.rs
> +use laplace_rs::{ObfCache};
The curly braces are superfluous.

2023-04-06 20:34 UTC, TKussel commented on src/util.rs
> +const ROUNDING_STEP: u64 = 10;
I would choose `usize` instead of `u64`

2023-04-06 20:34 UTC, TKussel commented on src/util.rs
> +                info!("patients");
Can you make the logging a bit more informative and less chatty, i.e. give a bit more context and demote to debug!?

2023-04-06 20:34 UTC, TKussel commented on src/util.rs
> +                info!("specimen");
same as above

2023-04-06 20:34 UTC, TKussel commented on src/util.rs
> +                info!("diagnosis");
same as above

2023-04-06 20:34 UTC, TKussel commented on src/util.rs
> +                warn!("focus is not aware of this type of stratifier")
maybe mention the result of this: "..., hence it will not obfuscate the values" or something like this.

2023-04-06 20:34 UTC, TKussel commented on src/util.rs
> +    //dbg!(measure_report_obfuscated.clone());
Please remove dead code

2023-04-06 20:34 UTC, TKussel commented on src/util.rs
> +                        *count_val = json!(10);
This, ultimately, should be handled by laplace-rs.

2023-04-06 20:34 UTC, TKussel commented on src/util.rs
> +                        .unwrap();
Are you sure this is safe? Please double-check, if this must be handled.

2023-04-06 20:34 UTC, TKussel commented on src/util.rs
> +    "#;
I would argue, that this test json could be compacted.

2023-04-12 11:43 UTC, enola-dkfz commented on src/main.rs
>      //debug!("_________________________________________________________");
Done

2023-04-12 11:43 UTC, enola-dkfz commented on src/main.rs
> +use laplace_rs::{ObfCache};
Done

2023-04-12 11:43 UTC, enola-dkfz commented on src/util.rs
> +const ROUNDING_STEP: u64 = 10;
Done

2023-04-12 11:44 UTC, enola-dkfz commented on src/util.rs
> +                info!("patients");
Done

2023-04-12 11:44 UTC, enola-dkfz commented on src/util.rs
> +                info!("specimen");
Done

2023-04-12 11:44 UTC, enola-dkfz commented on src/util.rs
> +                warn!("focus is not aware of this type of stratifier")
Done

2023-04-12 11:44 UTC, enola-dkfz commented on src/util.rs
> +    //dbg!(measure_report_obfuscated.clone());
Done

2023-04-12 11:44 UTC, enola-dkfz commented on src/util.rs
> +                        *count_val = json!(10);
Done

2023-04-12 11:44 UTC, enola-dkfz commented on src/util.rs
> +                        .unwrap();
Done

2023-04-25 20:39 UTC, TKussel approved these changes

2023-04-25 20:40 UTC, merged