Chore/max db attempts cla
samply/focus pull request #172
Opened 2024-10-10 11:19 UTC by enola-dkfz

2024-10-10 11:28 UTC, davidmscholz approved these changes

2024-10-10 11:57 UTC, Threated requested changes
Im not against it but rename it to `max_db_attempts` or something like it

2024-10-10 12:04 UTC, enola-dkfz commented
> Im not against it but rename it to `max_db_attempts` or something like it

done

2024-10-11 10:13 UTC, Threated approved these changes

2024-10-11 10:42 UTC, merged