obfuscation is now turnoffable
samply/focus pull request #20
Opened 2023-05-19 13:03 UTC by enola-dkfz

2023-05-20 15:40 UTC, lablans requested changes

2023-05-20 15:40 UTC, lablans commented on README.md
> +To disable the count obfuscation, set the env. variable `DO_NOT_OBFUSCATE`.
Please give values for on / off.

Consider using a positive variable (negations are confusing)

2023-05-20 15:40 UTC, lablans commented on src/config.rs
> +    #[clap(long, env, value_parser)]
Don't you want to set default value == false (meaning "yes, obfuscate?)

negations are confusing

2023-05-20 15:40 UTC, lablans commented on src/main.rs
> +    dbg!(cql_result_new.clone());
Forgot to remove?

2023-05-20 19:57 UTC, enola-dkfz commented on src/main.rs
> +    dbg!(cql_result_new.clone());
Removed

2023-05-20 19:58 UTC, enola-dkfz commented on src/config.rs
> +    #[clap(long, env, value_parser)]
When the parameter is not present, it is false, no default needed

2023-05-20 19:59 UTC, enola-dkfz commented on README.md
> +To disable the count obfuscation, set the env. variable `DO_NOT_OBFUSCATE`.
It doesn't work with boolean. 
https://github.com/clap-rs/clap/issues/1649
Do you want it to be a string?

2023-05-22 07:12 UTC, lablans commented on README.md
> +To disable the count obfuscation, set the env. variable `DO_NOT_OBFUSCATE`.
Surprising but then I'm fine with it

2023-05-22 13:45 UTC, TKussel approved these changes
With all concerns of @lablans addressed, this looks fine.

2023-05-22 16:37 UTC, merged