fix help and focusdev from debug
samply/focus pull request #66
Opened 2023-10-20 14:12 UTC by enola-dkfz

2023-10-20 14:14 UTC, lablans requested changes

2023-10-20 14:14 UTC, lablans commented on dev/focusdev
> +    FOCUS=./target/debug/focus
Why are you changing this?

2023-10-20 14:14 UTC, lablans commented on dev/focusdev
> +    docker compose logs -f
same here

2023-10-20 14:15 UTC, TKussel approved these changes
Assuming a debug build for local dev environment is sensible!

2023-10-20 14:16 UTC, Threated commented on dev/focusdev
> +    FOCUS=./target/debug/focus
This is changed because this is just for debugging in beamdev this is also debug

2023-10-20 14:19 UTC, Threated approved these changes
Fixes #60

2023-10-20 14:22 UTC, Threated commented on dev/focusdev
> +    docker compose logs -f
If you want more logs you can change it to `docker compose logs focus blaze -f`. Keep in mind if you want you can always `cd dev && docker compose logs -f` when you need to debug other stuff

2023-10-20 14:44 UTC, enola-dkfz commented on dev/focusdev
> +    docker compose logs -f
I'm just going to revert it

2023-10-23 06:47 UTC, lablans approved these changes

2023-10-23 06:47 UTC, merged