Deploy/omop
samply/focus pull request #88
Opened 2023-12-12 10:04 UTC by enola-dkfz

tested locally, works with both ENDPOINT_URL and with BLAZE_URL

2023-12-12 16:27 UTC, Threated requested changes

2023-12-12 16:27 UTC, Threated commented on src/main.rs
> +    }
use if let

2023-12-12 16:27 UTC, Threated commented on src/main.rs
> +    }
if let

2023-12-12 16:27 UTC, Threated commented on src/omop.rs
> +    }
if let

2023-12-12 16:27 UTC, Threated commented on src/omop.rs
> +        HeaderValue::from_str("application/json")
I think there is HeaderValue::from_static which does not error and is const

2023-12-12 18:53 UTC, enola-dkfz commented on src/main.rs
> +    }
done

2023-12-12 18:53 UTC, enola-dkfz commented on src/main.rs
> +    }
done

2023-12-12 18:53 UTC, enola-dkfz commented on src/omop.rs
> +    }
done

2023-12-12 18:53 UTC, enola-dkfz commented on src/omop.rs
> +        HeaderValue::from_str("application/json")
done

2023-12-12 19:12 UTC, enola-dkfz commented on src/main.rs
> +        let claiming = tokio::task::spawn(async move { beam::claim_task(&task_cloned).await });
Reverted it because it broke it and it's a deploy branch (though probably not automatic deploy)

2023-12-13 07:41 UTC, TKussel requested changes

2023-12-13 07:41 UTC, TKussel commented on src/omop.rs
We should rename that file, as we are not really performing OMOP queries here. I would defer changing the env-arg enum and the task-body `lang` value as that would be a breaking change that needs to be coordinated, but internally I would prefer to not speak of OMOP for the current changes.

2023-12-13 07:41 UTC, TKussel commented on src/omop.rs
> +    debug!("{}", ast_string.clone());
Please remove debug outputs printing large amounts of data (such as whole queries)

2023-12-13 07:41 UTC, TKussel commented on src/omop.rs
> +    debug!("Posting AST...");
Please check, how those debug messages can be made more useful.

2023-12-13 07:41 UTC, TKussel commented on src/omop.rs
> +    pub query: String,
Can that be consolidated with `Query`?

2023-12-13 07:41 UTC, TKussel commented on src/main.rs
> +    }
This is ok for now, but we should note down to refactor this in a more type-safe manner, instead of relying on string manipulation.

2023-12-13 07:41 UTC, TKussel commented on src/main.rs
> +fn parse_query(task: &BeamTask) -> Result<blaze::Query, FocusError> {
This only operates on blaze-cql queries, right? Maybe rename the function.

2023-12-13 07:41 UTC, TKussel commented on src/main.rs
> +        let query_decoded = general_purpose::STANDARD
A type alias from `general_purpose::STANDARD` to something like `Base64` (this one probably conflicts) might improve readability

2023-12-13 08:01 UTC, Threated commented on src/omop.rs
> +    debug!("{}", ast_string.clone());
On which log level is focus running in prod? If it's info I think it's fine otherwise this debug! could be set to trace! maybe

2023-12-13 10:24 UTC, enola-dkfz commented on src/omop.rs
> +    debug!("Posting AST...");
Like by adding the entire query?

2023-12-13 10:26 UTC, enola-dkfz commented on src/omop.rs
> +    pub query: String,
Of course it's not mathematically impossible, but would be ugly as fuck and in the future they'll all be AST anyway

2023-12-13 10:28 UTC, enola-dkfz commented on src/main.rs
> +    }
of course, that was quick-and-dirty fix because of the deadline, and then it stayed that way for months

2023-12-13 10:44 UTC, enola-dkfz commented on src/main.rs
> +        let query_decoded = general_purpose::STANDARD
![image](https://github.com/samply/focus/assets/115070135/b5870f47-ea8b-473e-850f-949c9e4ffa13)

2023-12-13 10:56 UTC, enola-dkfz commented on src/omop.rs
> +    debug!("{}", ast_string.clone());
Removed

2023-12-13 10:57 UTC, enola-dkfz commented on src/main.rs
> +fn parse_query(task: &BeamTask) -> Result<blaze::Query, FocusError> {
Done

2023-12-13 10:57 UTC, enola-dkfz commented on src/omop.rs
Done

2023-12-13 11:35 UTC, TKussel commented on src/omop.rs
> +    debug!("Posting AST...");
Like, by adding a beam task id and the endpoint url?

2023-12-13 11:36 UTC, TKussel commented on src/omop.rs
> +    pub query: String,
Good point, due to consolidating all query translation in focus, this is moot rather soon

2023-12-13 11:39 UTC, TKussel commented on src/main.rs
> +        let query_decoded = general_purpose::STANDARD
You are right, it's not a type but a public constant https://docs.rs/base64/0.21.5/src/base64/engine/general_purpose/mod.rs.html#332

2023-12-13 11:39 UTC, TKussel approved these changes

2023-12-13 11:41 UTC, Threated commented on src/main.rs
> +        let query_decoded = general_purpose::STANDARD
You can do something like use something::CONSTANT as BASE64 though

2023-12-13 11:42 UTC, enola-dkfz commented on src/omop.rs
> +    debug!("Posting AST...");
I would have to change this function's signature just for logging the task id and I already do this in main
 debug!("Processing task {}", task.id);

2023-12-13 11:50 UTC, Threated commented on src/omop.rs
> +    debug!("Posting AST...");
I mean you could just put the debug right before calling this function or you could use a tracing span but option 1 is probably simpler

2023-12-13 11:54 UTC, enola-dkfz commented on src/omop.rs
> +    debug!("Posting AST...");
Yeah, I log it already in main, if a need arises in the future, I'm gonna add it

2023-12-13 11:55 UTC, Threated approved these changes

2023-12-13 11:56 UTC, enola-dkfz commented on src/main.rs
> +        let query_decoded = general_purpose::STANDARD
Thx

2023-12-13 13:21 UTC, merged